services:
  publisher:
    routes:
      - name: prophet_xml_import
        route: "/api/v1/playlists/prophet_xml_import/<stream>/"
        method: "GET"
        params:
          - xml_contents
      - name: david_xml_import
        route: "/api/v1/playlists/david_xml_import/<stream>/"
        method: "POST"
        params:
          - password
  whats-on:
    routes:
      - name: whats_on_prophet
        route: "/whats-on/v1/update"
        method: "GET"
        params:
          - xml_contents
          - stream
      - route: "/whats-on/v1/update"
        method: "POST"
        params:
          - stream

tests:
  - test_prophet_import:
      send: "GET"
      target: publisher.prophet_xml_import
      vars:
        stream: wqxr
      expect: 
        - prophet_xml_import:
            called_times: 1
            method: "GET"
            return_status: 200
            called_with: 
              params: 
                stream: wqxr
        - whats_on_prophet:
            called_times: 1
            method: "GET"
            return_status: 200
            called_with: 
              params: 
                stream: wqxr
